# Generated by Django 2.2.5 on 2019-11-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('saddress', models.CharField(max_length=50)),
                ('sfees', models.FloatField()),
                ('scollege', models.CharField(max_length=50)),
                ('sage', models.IntegerField()),
            ],
        ),
    ]
